// <auto-generated />
using System;
using MeuTeste.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuTeste.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MeuTesteDbContext))]
    partial class MeuTesteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeuTeste.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            IsDelete = false,
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            IsDelete = false,
                            Name = "Livros"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            IsDelete = false,
                            Name = "Roupas"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            IsDelete = false,
                            Name = "Alimentos"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            IsDelete = false,
                            Name = "Casa e Jardim"
                        });
                });

            modelBuilder.Entity("MeuTeste.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new { Id = 1, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 1", Price = 100m },
                        new { Id = 2, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 2", Price = 150m },
                        new { Id = 3, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 3", Price = 200m },
                        new { Id = 4, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 4", Price = 250m },
                        new { Id = 5, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 5", Price = 300m },
                        new { Id = 6, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 6", Price = 350m },
                        new { Id = 7, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 7", Price = 400m },
                        new { Id = 8, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 8", Price = 450m },
                        new { Id = 9, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 9", Price = 500m },
                        new { Id = 10, CategoryId = 1, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Eletrônico 10", Price = 550m },
                        new { Id = 11, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 1", Price = 30m },
                        new { Id = 12, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 2", Price = 40m },
                        new { Id = 13, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 3", Price = 50m },
                        new { Id = 14, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 4", Price = 60m },
                        new { Id = 15, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 5", Price = 70m },
                        new { Id = 16, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 6", Price = 80m },
                        new { Id = 17, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 7", Price = 90m },
                        new { Id = 18, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 8", Price = 100m },
                        new { Id = 19, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 9", Price = 110m },
                        new { Id = 20, CategoryId = 2, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Livro 10", Price = 120m },
                        new { Id = 21, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 1", Price = 50m },
                        new { Id = 22, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 2", Price = 65m },
                        new { Id = 23, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 3", Price = 80m },
                        new { Id = 24, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 4", Price = 95m },
                        new { Id = 25, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 5", Price = 110m },
                        new { Id = 26, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 6", Price = 125m },
                        new { Id = 27, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 7", Price = 140m },
                        new { Id = 28, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 8", Price = 155m },
                        new { Id = 29, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 9", Price = 170m },
                        new { Id = 30, CategoryId = 3, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Roupa 10", Price = 185m },
                        new { Id = 31, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 1", Price = 10m },
                        new { Id = 32, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 2", Price = 15m },
                        new { Id = 33, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 3", Price = 20m },
                        new { Id = 34, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 4", Price = 25m },
                        new { Id = 35, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 5", Price = 30m },
                        new { Id = 36, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 6", Price = 35m },
                        new { Id = 37, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 7", Price = 40m },
                        new { Id = 38, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 8", Price = 45m },
                        new { Id = 39, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 9", Price = 50m },
                        new { Id = 40, CategoryId = 4, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Alimento 10", Price = 55m },
                        new { Id = 41, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 1", Price = 25m },
                        new { Id = 42, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 2", Price = 45m },
                        new { Id = 43, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 3", Price = 65m },
                        new { Id = 44, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 4", Price = 85m },
                        new { Id = 45, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 5", Price = 105m },
                        new { Id = 46, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 6", Price = 125m },
                        new { Id = 47, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 7", Price = 145m },
                        new { Id = 48, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 8", Price = 165m },
                        new { Id = 49, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 9", Price = 185m },
                        new { Id = 50, CategoryId = 5, CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc), CreatedUser = "system", IsDelete = false, Name = "Item Casa e Jardim 10", Price = 205m });
                });

            modelBuilder.Entity("MeuTeste.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedUser = "system",
                            Email = "vladimirca2000@gmail.com",
                            IsActive = true,
                            IsApproved = true,
                            IsDelete = false,
                            PasswordHash = "fTH3iZVqKFLpI+C3/wHNVfVDLqX2gDfXlYNQKrWlqJU=",
                            Role = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MeuTeste.Domain.Entities.Product", b =>
                {
                    b.HasOne("MeuTeste.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MeuTeste.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
